# Configuração de serviços
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ch4ng3m3!
      DB_NAME: rview
    networks:
      - rview_network
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"  # Mapeia a porta do Vite
    networks:
      - rview_network
    volumes:
      - ./frontend:/app  # Mapeia o código local para o contêiner
      - /app/node_modules  # Evita conflitos com node_modules local
    stdin_open: true
    tty: true

    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ch4ng3m3!
      POSTGRES_DB: rview
    ports:
      - "5432:5432"
    networks:
      - rview_network
    volumes:
      - pgdata:/var/lib/postgresql/data

# Configuração de volumes
volumes:
  pgdata:

# Configuração de rede
networks:
  rview_network:
    driver: bridge
